version: "2"

volumes:
    server-data:
        driver: local

services:
    sherlockohms-telegram-bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: ghcr.io/nevse/sherlockohms-telegram-bot:master
        container_name: sherlockohms-telegram-bot
        hostname: sherlockohms-telegram-bot
        restart: always

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        environment:
            - TELEGRAM_TOKEN
            - TELEGRAM_SERVER=http://telegram-bot-api:8081

    # This service is optional.
    # It could be accessed by port 8081 as local Telegram Bot API server.
    telegram-bot-api:
        image: ghcr.io/bots-house/docker-telegram-bot-api:latest
        container_name: telegram-bot-api
        hostname: telegram-bot-api
        command: "--dir=/var/lib/telegram-bot-api"
        volumes:
            - server-data:/var/lib/telegram-bot-api
        restart: unless-stopped

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        environment:
            # get these values from https://core.telegram.org/api/obtaining_api_id
            - TELEGRAM_API_ID
            - TELEGRAM_API_HASH
