name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: setup .NET 9.x
      uses: actions/setup-dotnet@v3
      with:
        # Semantic version range syntax or exact version of a dotnet version
        dotnet-version: '9.x'

    - name: build the project
      run: dotnet build src/TelegramBot.csproj 
    
    - name: set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: build and deploy master image to ghcr.io
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        USERNAME: ${{ github.actor }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
        echo GITHUB_REF - $ref
        echo ${GH_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
        docker buildx build --push \
            --build-arg CI=github --build-arg GITHUB_SHA=${GITHUB_SHA} --build-arg GIT_BRANCH=${ref} \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/nevse/sherlockohms-telegram-bot:${ref} .

